---
title: "Preliminary Processing of Movement Data"
author: "Elie Gurarie"
date: "August 22, 2016"
output: html_document
---

```{r eval=FALSE, echo=FALSE}
setwd("c:/users/elie/Box Sync/teaching/AukeBay Movement/Day1/Lecture1")
require(rmarkdown)
render("Lecture1.Rmd")
shell("Lecture1.html")
```

## Data processing ...
is the least loved and most time consuming aspect of any data analysis! 

It is also **unavoidable** and **extremely important**. 


## Goals

### Facilitate Analysis!
	

## Principles

### Smart data processing is:

- **compartamentalized** - e.g. each step a function
- **interactive** - leverage visualization and interactive tools
- **generalizable** - to apply to multiple individuals
- **replicable** - *important: NEVER overwrite the raw data!*
- **well-documented** - so you don't have to remember what you did
- **forgettable!** - so once its done you don't need to think about it any more

##  Tools

Several packages are particularly useful for data processing and clean-up:

- `plyr` - manipulating data frames and lists
 - functions: `mutate()`; `ddply()`-`ldply()`-`dlply()`
- `lubridate` - manipulating time objects
- `rgdal` - projecting coordinates
- `maps` and `mapdata` - quick and easy maps
-  `magrittr` - for *piping*

## Example: short-toed eagle (*circaetus gallicus*)

<center>
<image src = "shorttoedeagle.jpg" width = 700/>
</center>
Data: Ugo Mellone - Universidad de Alicante, Spain